version: '3.3'

services:
  web:
    build:
      context: .
      args:
        - FLASK_ENV=production
    restart: always
    volumes:
      - /var/catastro:/catastro
    ports:
      - "5000:5000"
    expose:
      - "5000"
    networks:
      default:
        aliases:
          - api

networks:
  default:
    external:
      name: catatom

